repos:
  - repo: https://github.com/ambv/black
    rev: 23.11.0
    hooks:
      - id: black
        args: [--config, pyproject.toml]
        exclude: "{{ cookiecutter.project_slug }}"
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.5
    hooks:
      - id: ruff
        args: [--config, pyproject.toml, --fix, --exit-non-zero-on-fix]
        exclude: "{{ cookiecutter.project_slug }}"
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.0
    hooks:
      - id: mypy
        args: [--config, pyproject.toml]
        exclude: "{{ cookiecutter.project_slug }}"
